"""empty message

Revision ID: 21216a37cbab
Revises: aef646628979
Create Date: 2020-04-07 19:12:14.357351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21216a37cbab'
down_revision = 'aef646628979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
