"""empty message

Revision ID: 652c307fb26a
Revises: f1b598bf425b
Create Date: 2020-04-07 19:32:58.823381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652c307fb26a'
down_revision = 'f1b598bf425b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
